theme: jekyll-theme-merlot
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title> Dungeons & Dragons </title>
    <link rel="stylesheet" href="css/stule.css">
</head>
<body>
    <header>
        <div class="header-bg">
            <img src="лог0.png" width="1000" height="120">
        </div>
    </header>
    <h1>
        Материал для ознакомления
    </h1>
    Dungeons & Dragons (дословно — «Подземелья и драконы», сокращается до D&D или DnD) — настольная ролевая игра в стиле фэнтези, выпускаемая компанией Wizards of the Coast. Это не только первая, но и самая популярная система ролевых игр в мире, пережившая много переизданий и изменений.
    <br><br>Придуманная в 1970 и выпущенная в январе 1974 года первая редакция D&D была и самой первой ролевой игрой в мире. Правила для неё придумал Гэри Гигакс на основе правил своей военно-тактической игры Chainmail, доработав её ролевую составляющую вместе с Дэйвом Арнесоном. На правила оказали влияние настольные стратегические игры 50-60-х годов, главным образом военно-тактические игры с миниатюрами, в которых отдельные боевые единицы отображались на столе при помощи фигурок.
    <br><br>В виду распространения COVID-19, кампания Wizards of the Coast работает из дома, и продолжает создавать новые истории D&D и дополнения поклонников данной вселенной во всем мире.
    Социальные связи в играх, включая D&D, могут продолжать быть полезными для тех из нас, кто чувствует себя изолированным или одиноким в наших домах, чтобы оставаться в безопасности от передачи инфекции. Поскольку социальное дистанцирование влияет на нашу способность собираться вместе лично, Визарды решили создать ресурсы и советы для удаленной игры.
    В качестве дополнительного ресурса для геймеров команда D&D рада предложить следующие материалы в качестве бесплатных приключений и ресурсов для использования в ваших играх—независимо от того, играете ли вы в кампании кухонного стола, являетесь ли вы активным участником Лиги D&D Adventurers League или просто заинтересованы в том, чтобы узнать больше о Dungeons & Dragons и попробовать его на себе.
    Кроме того, в связи с закрытием школ по всему миру многие родители и воспитатели находятся дома со своими детьми, в том числе многие из сообщества D&D. Если вы нуждаетесь в веселых и образовательных материалах, чтобы поделиться ими и / или поиграть со своими детьми, вы можете проверить здесь материалы D&D, чтобы помочь в течение этого времени. И если вы (или кто-то из ваших знакомых) - молодой геймер, мы также выпускаем ресурсы, чтобы еще легче было попасть в D&D.
    <br><br>
    <a href="https://hobbygames.ru/dungeons-and-dragons"><img src="DNDshss.png"></a>
 </body>
</html>
